stages:
  - build
  - deploy

sem_telegram_bot_production_build:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  stage: build
  script:
    - cd bot
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/nikitamelnikwork/sem:bot .
    - docker push registry.gitlab.com/nikitamelnikwork/sem:bot
  only:
    - 0.2.4

sem_messenger_production_build:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  stage: build
  script:
    - cd messenger
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/nikitamelnikwork/sem:messenger .
    - docker push registry.gitlab.com/nikitamelnikwork/sem:messenger
  only:
    - 0.2.4

sem_production_deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$REMOTE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${REMOTE_USER}@${REMOTE_HOST} "cd ${REMOTE_ROOT};docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD;docker compose up --build -d sem-telegram-bot sem-messenger;docker logout;docker restart nginx;docker system prune -f"
  only:
    - 0.2.4
