services:
  nexie-socials-agent:
    build: ./socials-agent
    container_name: nexie_socials_agent
    shm_size: '1gb'
    networks:
      - nexie_network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - ./data:/app/data
    env_file:
      - ./socials-agent/.env
    ports:
      - "3000:3000"
  nexie-telegram-bot:
    build: ./telegram-bot
    container_name: nexie_telegram_bot
    networks:
      - nexie_network
    volumes:
      - ./data:/app/data
    env_file:
      - ./telegram-bot/.env
  nexie-messenger:
    build: ./messenger
    container_name: nexie_messenger
    networks:
      - nexie_network
    ports:
      - "80:80"

networks:
  nexie_network:
    driver: bridge